server:
  port: 8000
spring:
  thymeleaf:
    cache: false
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/showcook
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: update

